### ISSUE TITLE
Is this extension requires  permission for read search history?

### ISSUE THREAD

**Issue by roharon** [fhefh2015/GitHub1s_chrome_extension#1]
First, thanks for deploy good extension.
but I have one question about permission.

Chrome browser alerts to me like this, `To use this Extension, accept new permission - read search history` 
(I used korean locale, so the alert message is not really same as original locale message)

Could you inform me about which operation need reading search history?

**Comment by fhefh2015** [comment]
I only use these three permissions

```javascript
 "permissions": [
    "storage",
    "contextMenus",
    "tabs" //get the current and open the new tab near the current tab
  ]
```
Why does my chrome extension ask for history permissions?
https://stackoverflow.com/questions/40660407/why-does-my-chrome-extension-ask-for-history-permissions

Declare permissions and warn users - Chrome Developers 
https://developer.chrome.com/docs/extensions/mv2/permission_warnings/ 

Hope the above content can help you.
-------------
I'm so sorry for that, i have changed the permission to activeTab.
the version 0.2.4, please upgrade it

**Comment by roharon** [comment]
Thanks for fast replying :)
