### ISSUE TITLE
support private repo

### ISSUE THREAD

**Issue by wwwenjie** [fhefh2015/GitHub1s_chrome_extension#11]
seems like this extension block private repo in https://github.com/fhefh2015/GitHub1s_chrome_extension/blob/main/github1s/src/content/content.js#L61
can we add a option to allow the button show in private repo?

**Comment by fhefh2015** [comment]
![CleanShot 2021-08-04 at 14 30 19@2x](https://user-images.githubusercontent.com/14891797/128132795-4e4516e9-457c-421f-b530-6a218a72bd04.png)

**Comment by wwwenjie** [comment]
sorry i missed it... thanks for pointing out.
