### ISSUE TITLE
Some changes are not applied yet

### ISSUE THREAD

**Issue by ghost** [fhefh2015/GitHub1s_chrome_extension#12]
Keeping branch #5 and Open directories and files #10 is merged, but the latest version of this extension in the [Chrome Web Store](https://chrome.google.com/webstore/detail/github1s/lodjfmkfbfkpdhnhkcdcoonghhghbkhe) is still old, can you upload a new one?

**Comment by fhefh2015** [comment]
Updated~

**Comment by ghost** [comment]
Thank you!
