### ISSUE TITLE
Add feature to add custom keyboard shortcut to open code in Github1s

### ISSUE THREAD

**Issue by donenoyes** [fhefh2015/GitHub1s_chrome_extension#3]
Custom Keyboard shortcut for opening code in Github1s would be great. Currently the extension only supports button on Github repo and the context menu option.

**Comment by fhefh2015** [comment]
Great idea, I will implement this feature in the next version.

**Comment by fhefh2015** [comment]
@jiayounokim 

chrome is being reviewed

![image](https://user-images.githubusercontent.com/14891797/108682902-de62ea00-752b-11eb-8572-4b66268f422d.png)
