### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Maxim-Mazurok** [fhefh2015/GitHub1s_chrome_extension#8]
No errors in the console, but it doesn't add a button anymore.
Tried to disable other extensions, no luck :(

**Comment by fhefh2015** [comment]
Bug fixed, please check v0.3.5. 
chrome store is still under review

**Comment by Maxim-Mazurok** [comment]
Thank you for quick fix, I'll wait for the review

**Comment by Maxim-Mazurok** [comment]
It works now, thanks! :)
